name: ChipsUHC
author: NullChips
version: 1.0
main: me.nullchips.chipsuhc.ChipsUHC

commands:
  test:
    description: A test command for testing stuff init.
  start:
    description: Starts the UHC game.
  cancel:
    description: Cancel the start command. This prevents the start command from being inputted twice.
  gmc:
    description: Change gamemode to creative.
  gms:
    description: Change gamemode to survival.
  clear:
    description: Clear a player's inventory.
    aliases: [ci]
  heal:
    description: Heal a player.
  feed:
    description: Feed a player.
  helpop:
    description: Send a message to a host.
  giveall:
    description: Give all players an item.
  health:
    description: Get a player's health.
  muteall:
    description: Mute all players.
  mute:
    description: Mute a player.
  unmute:
    description: Unmute a player.
  features:
    description: Get the state of features.
  createteam:
    description: Create a team.
  removeteam:
    description: Remove a team.
  removefromteam:
    description: Remove a player from a team.
  addtoteam:
    description: Add a player to a team.

permissions:
  uhc.start:
    description: Start the UHC game.
    default: op
  uhc.changegamemode:
    description: Change player's own gamemode.
    default: op
  uhc.clear:
    description: Clear a player's inventory.
    default: op
  uhc.heal:
    description: Heal a player.
    default: op
  uhc.feed:
    description: Feed a player.
    deafault: op
  uhc.helpop:
    description: See helpop messages.
    default: op
  uhc.giveall:
    description: Give all players an item.
    default: op
  uhc.mute:
    description: Mute players.
    default: op
  uhc.bypassmute:
    description: Bypass a mute.
    default: op
  uhc.bypassglobalmute:
    description: Bypass the global mute.
    default: op
  uhc.getfeatures:
    description: Get the state of the features.
    default: true
  uhc.modifyteams:
    description: Modify the contents of teams.
    default: op